# Generated by Django 2.2.1 on 2019-05-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20190521_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='Professsion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='date_employed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='id_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
